<?php
/**
 * Maintenance mode control.
 *
 * @package SHCM
 */

namespace SHCM\Import;

use SHCM\Filesystem\Paths;

defined( 'ABSPATH' ) || exit;

/**
 * Puts the site into WordPress maintenance mode for the duration of a restore.
 *
 * WordPress expires its own .maintenance file after ten minutes, which is
 * exactly the safety net we want: if a restore dies in a way that skips every
 * cleanup path, the site comes back by itself. The timestamp is therefore
 * refreshed on each tick rather than written once.
 */
class MaintenanceMode {

	const FLAG_FILE = '.maintenance';
	const TEMPLATE  = 'shcm-maintenance.php';

	/**
	 * Path of the maintenance flag.
	 *
	 * @return string
	 */
	public static function flagPath() {
		return Paths::abspath() . '/' . self::FLAG_FILE;
	}

	/**
	 * Path of the custom maintenance page.
	 *
	 * @return string
	 */
	public static function templatePath() {
		return Paths::contentDir() . '/maintenance.php';
	}

	/**
	 * Marker recording that this plugin owns the maintenance files.
	 *
	 * @return string
	 */
	protected static function markerPath() {
		return Paths::contentDir() . '/' . \SHCM\Filesystem\Storage::DIR_NAME . '/maintenance.marker';
	}

	/**
	 * Turn maintenance mode on (or refresh its timestamp).
	 *
	 * @param string $message Message shown to visitors.
	 * @return bool
	 */
	public static function enable( $message = '' ) {
		$flag = self::flagPath();
		if ( ! is_writable( dirname( $flag ) ) && ! is_writable( $flag ) ) {
			return false;
		}

		$written = false !== @file_put_contents( $flag, '<?php $upgrading = ' . time() . '; // SH Clone Migration' . "\n" );
		if ( ! $written ) {
			return false;
		}

		$template = self::templatePath();
		if ( ! file_exists( $template ) || is_file( self::markerPath() ) ) {
			$body = self::page( $message );
			if ( false !== @file_put_contents( $template, $body ) ) {
				@file_put_contents( self::markerPath(), (string) time() );
			}
		}

		return true;
	}

	/**
	 * Turn maintenance mode off.
	 *
	 * @return void
	 */
	public static function disable() {
		$flag = self::flagPath();
		if ( file_exists( $flag ) ) {
			@unlink( $flag );
		}
		// Only remove the maintenance page if this plugin created it.
		if ( is_file( self::markerPath() ) ) {
			if ( file_exists( self::templatePath() ) ) {
				@unlink( self::templatePath() );
			}
			@unlink( self::markerPath() );
		}
	}

	/**
	 * Whether maintenance mode is currently on.
	 *
	 * @return bool
	 */
	public static function isEnabled() {
		return file_exists( self::flagPath() );
	}

	/**
	 * The maintenance page shown to visitors.
	 *
	 * @param string $message Message.
	 * @return string
	 */
	protected static function page( $message ) {
		if ( '' === $message ) {
			$message = __( 'Website migration in progress. Please do not close this page.', 'sh-clone-migration' );
		}
		$escaped = esc_html( $message );

		return '<?php' . "\n"
			. '// Generated by SH Clone Migration. Removed automatically when the migration finishes.' . "\n"
			. 'http_response_code( 503 );' . "\n"
			. 'header( "Retry-After: 120" );' . "\n"
			. 'header( "Content-Type: text/html; charset=utf-8" );' . "\n"
			. '?>' . "\n"
			. '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
			. '<title>' . esc_html__( 'Migration in progress', 'sh-clone-migration' ) . '</title>'
			. '<style>body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;'
			. 'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f6f7f7;color:#1d2327}'
			. '.b{max-width:32rem;padding:2.5rem;text-align:center}h1{font-size:1.4rem;margin:0 0 .75rem}'
			. 'p{margin:0;color:#50575e;line-height:1.6}.s{width:2.5rem;height:2.5rem;margin:0 auto 1.5rem;border:3px solid #dcdcde;'
			. 'border-top-color:#2271b1;border-radius:50%;animation:r 1s linear infinite}@keyframes r{to{transform:rotate(360deg)}}</style>'
			. '</head><body><div class="b"><div class="s"></div><h1>' . $escaped . '</h1>'
			. '<p>' . esc_html__( 'The website will be back shortly.', 'sh-clone-migration' ) . '</p></div></body></html>';
	}
}
